[package]
name = "kobo-hal"
version.workspace = true
edition.workspace = true
publish = false
rust-version.workspace = true
license.workspace = true

[dependencies]
kobo-abi = { path = "../kobo-abi", default-features = false }
kobo-doc = { path = "../kobo-doc" }
kobo-profile = { path = "../kobo-profile" }
kobo-protocol = { path = "../kobo-protocol" }
minimp3 = "0.5.2"

[dev-dependencies]
kobo-handoff = { path = "../kobo-handoff" }

[features]
default = []
device-write = ["kobo-abi/device-write"]

[lints]
workspace = true
