[package]
name = "kobo-frame"
version = "1.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
blake3 = "1.8.2"
kobo-image = { path = "../../crates/kobo-image" }
kobo-sdk = { path = "../../crates/kobo-sdk" }

[dev-dependencies]
kobo-ui = { path = "../../crates/kobo-ui" }

[lints]
workspace = true
