[package]
name = "kobo-parser"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
kobo-sdk = { path = "../../crates/kobo-sdk", features = ["text"] }
kobo-zstory = { path = "../../crates/kobo-zstory" }

[dev-dependencies]
kobo-ui = { path = "../../crates/kobo-ui" }
kobo-text = { path = "../../crates/kobo-text" }

[lints]
workspace = true
