[package]
name = "kobo-birds"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
kobo-sdk = { path = "../../crates/kobo-sdk" }
kobo-image = { path = "../../crates/kobo-image" }
kobo-json = { path = "../../crates/kobo-json" }

[dev-dependencies]
kobo-ui = { path = "../../crates/kobo-ui" }

[lints]
workspace = true
