[package]
name = "kobo-needles"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
kobo-bookview = { path = "../../crates/kobo-bookview" }
kobo-json = { path = "../../crates/kobo-json" }
kobo-read = { path = "../../crates/kobo-read" }
kobo-sdk = { path = "../../crates/kobo-sdk" }

[dev-dependencies]
kobo-doc = { path = "../../crates/kobo-doc" }
kobo-ui = { path = "../../crates/kobo-ui" }

[lints]
workspace = true
