[package]
name = "kobo-homepanel"
version = "0.2.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
kobo-json = { path = "../../crates/kobo-json" }
kobo-sdk = { path = "../../crates/kobo-sdk" }

[dev-dependencies]
kobo-ui = { path = "../../crates/kobo-ui" }

[lints]
workspace = true
